import ReactQueryClientProvider from "@/lib/react-query-client-provider";
import ThemeProvider from "@/lib/theme-provider";
import StatusBar from "@/ui/statusbar";
import Stack from "@mui/material/Stack";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <ReactQueryClientProvider>
                <ThemeProvider>
                    <Stack component="body" height="100vh">
                        <StatusBar />
                        {children}
                    </Stack>
                </ThemeProvider>
            </ReactQueryClientProvider>
        </html>
    );
}
